#!/bin/sh
F=$1

gnuplot <<END
set terminal png size 1024,768
set yrange [0:]
set output "bro.png"
set ylabel "instructions"
set datafile separator ","

set xdata time
set timefmt "%s"
set timefmt "%Y-%m-%d %H:%M:%S -0800"
set format x "%Y-%m-%d"
#set xrange ["2013-06-01 00:00:00":"2013-09-01 00:00:00"]
set multiplot layout 2, 1 ;

set ylabel "seconds"
set yrange [6:]
plot "$F" using 2:4 with points title "Seconds"

set ylabel "instructions"
set yrange [30000000000.0:]
plot "$F" using 2:5 with points title "Instructions"

unset multiplot
END
